name: build

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          install: autoconf automake bison flex git
          update: true
      - shell: msys2 {0}
        run: |-
          bash -lc "autoreconf -i"
          bash -lc "./configure --with-oniguruma=builtin --disable-shared --enable-static --enable-all-static"
          bash -lc "make"
          bash -lc "cat jq.1  | groff -mandoc -Thtml > jq.html"
          7z a jq-package.zip jq.1 jq.html jq.exe
          bash -lc "pwd && ls -al"
          file jq.exe
      - uses: actions/upload-artifact@v2
        with:
          path: |-
            jq-package.zip
            jq.exe
